name: Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Package
        run: tar -czf fuzpad-${{ github.ref_name }}.tar.gz *

      - name: Generate Changelog
        id: changelog
        run: echo "Changelog for version ${{ github.ref_name }}" > CHANGELOG.md
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: steps.changelog.outcome == 'success'
        with:
          body_path: CHANGELOG.md
          files: fuzpad-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
