name: Tag Automation

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch: 

jobs:
  generate-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main 

      - name: Get the latest tag
        id: get-latest-tag
        run: echo "LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)" >> $GITHUB_ENV

      - name: Check for changes
        id: check-changes
        run: |
          git fetch
          CHANGED_FILES=$(git log ${{ env.LATEST_TAG }}..HEAD --format="%H" --reverse --no-merges)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected. Exiting."
            exit 0
          fi

      - name: Generate new tag
        id: new-tag
        run: |
          MAJOR_VERSION=$(echo ${{ env.LATEST_TAG }} | awk -F. '{print $1}')
          MINOR_VERSION=$(echo ${{ env.LATEST_TAG }} | awk -F. '{print $2}')
          NEW_MINOR_VERSION=$(printf "%02d" $((10#$MINOR_VERSION + 1)))
          NEW_TAG="$MAJOR_VERSION.$NEW_MINOR_VERSION.00"
          echo Latest: ${{ env.LATEST_TAG }}
          echo NEW: $NEW_TAG
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
