name: Update Homebrew Formula

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Get latest release tag
        id: get_latest_release
        env:
          GH_TOKEN: ${{ secrets.token }}
        run: |
          latest_release=$(gh release view --json tagName --jq '.tagName')
          echo "Latest release tag: $latest_release"
          echo "tag=$latest_release" >> $GITHUB_ENV

      - name: Update Homebrew Formula
        run: |
          SHA256=$(curl -sL https://github.com/JianZcar/FuzPad/releases/download/${{ env.tag }}/fuzpad-${{ env.tag }}.tar.gz | sha256sum | awk '{print $1}')
          
          cat > fuzpad.rb <<EOF
          class Fuzpad < Formula
            desc "Minimalistic note management solution. Powered by fzf"
            homepage "https://github.com/JianZcar/FuzPad"
            url "https://github.com/JianZcar/FuzPad/releases/download/${{ env.tag }}/fuzpad-${{ env.tag }}.tar.gz"
            sha256 "$SHA256"
            license "GPL-3.0-or-later"

            livecheck do
              url :stable
              strategy :github_latest
            end

            depends_on "bat"
            depends_on "fzf"

            def install
              bin.install "fuzpad"
            end

            test do
              assert_equal "1", shell_output("#{bin}/fuzpad --test 2>&1 | grep -q \"1\" && echo 1 || echo 0").strip
            end
          end
          EOF

      - name: Checkout homebrew-packages  repository
        uses: actions/checkout@v2
        with:
          repository: JianZcar/homebrew-packages 
          token: ${{ secrets.token }}
          path: homebrew-packages 

      - name: Move updated formula to homebrew-packages 
        run: |
          mv fuzpad.rb homebrew-packages/Formula/fuzpad.rb

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          cd homebrew-packages 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/fuzpad.rb
          git commit -m "Update Homebrew formula for version ${{ env.tag }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/JianZcar/homebrew-packages .git HEAD:main
